- name: Create http vhost for openvpn
  template:
    src: templates/nginx/openvpn.http.j2
    dest: "/etc/nginx/sites-enabled/{{ openvpn_hostname }}.http"
    owner: root
    group: root
    mode: '0644'

- name: Check that certificate exists
  stat: 
    path: "/var/lib/dehydrated/certs/{{ openvpn_hostname }}/fullchain.pem"
  register: cert_file

- name: Create https vhost for openvpn
  template:
    src: templates/nginx/openvpn.https.j2
    dest: "/etc/nginx/sites-enabled/{{ openvpn_hostname }}.https"
    owner: root
    group: root
    mode: '0644'
  when: cert_file.stat.exists
